//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export enum eEntityStatus {
	Active = 0,
	Deleted = 99
}
export enum eResource {
	Example = 0
}
export enum eAction {
	View = 1,
	Create = 2,
	Update = 4,
	Remove = 8,
	Delete = 16
}
